# Generated by Django 5.0 on 2023-12-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_genre_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confusing_elements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='connection_characters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='engaging_plot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='enjoyed_writing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='expectations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='influence_on_thoughts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='lasting_impression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='themes_resonated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='unexpected_twists',
            field=models.BooleanField(default=False),
        ),
    ]
