# Generated by Django 5.0 on 2023-12-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
